export const EVENT_DATA = [
  // Tech-Spardha Events
  {
    event_category: "tech-spardha",
    event_name: "code-sudoku",
    event_date: "2025-04-02",
    event_time: "11:00AM",
    event_organizer: "Tech Club",
    event_location: "Lab 101",
    event_description: "Solve complex Sudoku puzzles using programming.",
    event_image: "sudoku_event_poster",
    event_link: "registration_link",
    entry_fees: 100,
    prize_money: { first: 500, second: 300, third: 200 },
    event_requirement: "Bring your laptop with Python installed.",
    event_guidelines: ["No external help allowed", "Complete within 30 mins"],
  },
  {
    event_category: "tech-spardha",
    event_name: "bug-hunting",
    event_date: "2025-04-03",
    event_time: "2:00PM",
    event_organizer: "Cyber Club",
    event_location: "Lab 202",
    event_description: "Find and fix bugs in given programs.",
    event_image: "bug_hunting_poster",
    event_link: "registration_link",
    entry_fees: 120,
    prize_money: { first: 700, second: 400, third: 300 },
    event_requirement: "Basic knowledge of debugging tools.",
    event_guidelines: ["Code must compile", "Justify the fixes"],
  },
  {
    event_category: "tech-spardha",
    event_name: "code-what-you-saw",
    event_date: "2025-04-04",
    event_time: "12:00PM",
    event_organizer: "AI Club",
    event_location: "Lab 303",
    event_description: "Recreate code based on given outputs.",
    event_image: "code_what_you_saw_poster",
    event_link: "registration_link",
    entry_fees: 150,
    prize_money: { first: 800, second: 500, third: 200 },
    event_requirement: "Knowledge of Python and JavaScript.",
    event_guidelines: ["No internet usage", "Follow syntax correctly"],
  },
  {
    event_category: "tech-spardha",
    event_name: "hackathon",
    event_date: "2025-04-05",
    event_time: "10:00AM",
    event_organizer: "Innovation Hub",
    event_location: "Main Hall",
    event_description:
      "Build a project in a limited time based on given themes.",
    event_image: "hackathon_poster",
    event_link: "registration_link",
    entry_fees: 200,
    prize_money: { first: 1000, second: 600, third: 400 },
    event_requirement: "Teams of 2-4 members required.",
    event_guidelines: ["No prebuilt projects", "Use open-source tools"],
  },
  {
    event_category: "tech-spardha",
    event_name: "AI-Challenge",
    event_date: "2025-04-06",
    event_time: "3:00PM",
    event_organizer: "AI Club",
    event_location: "Lab 404",
    event_description: "Develop AI models for real-world problems.",
    event_image: "ai_challenge_poster",
    event_link: "registration_link",
    entry_fees: 180,
    prize_money: { first: 900, second: 500, third: 300 },
    event_requirement: "Experience with AI/ML libraries.",
    event_guidelines: ["Code must be original", "Dataset must be open-source"],
  },

  // Kala-Utsav Events
  {
    event_category: "kala-utsav",
    event_name: "painting-contest",
    event_date: "2025-04-02",
    event_time: "11:30AM",
    event_organizer: "Art Club",
    event_location: "Art Room",
    event_description: "Showcase your creativity in painting.",
    event_image: "painting_event_poster",
    event_link: "registration_link",
    entry_fees: 80,
    prize_money: { first: 400, second: 250, third: 150 },
    event_requirement: "Participants must bring their own painting materials.",
    event_guidlines: ["No digital paintings", "Canvas size limited to A3"],
  },
  {
    event_category: "kala-utsav",
    event_name: "sketching-challenge",
    event_date: "2025-04-03",
    event_time: "1:00PM",
    event_organizer: "Creative Arts Society",
    event_location: "Art Gallery",
    event_description: "Create beautiful sketches within a limited time.",
    event_image: "sketching_event_poster",
    event_link: "registration_link",
    entry_fees: 70,
    prize_money: { first: 350, second: 200, third: 100 },
    event_requirement: "Pencils and erasers allowed.",
    event_guidlines: ["No tracing", "Time limit is 1 hour"],
  },
  {
    event_category: "kala-utsav",
    event_name: "dance-competition",
    event_date: "2025-04-04",
    event_time: "5:00PM",
    event_organizer: "Dance Club",
    event_location: "Auditorium",
    event_description: "A platform to showcase your dancing skills.",
    event_image: "dance_competition_poster",
    event_link: "registration_link",
    entry_fees: 100,
    prize_money: { first: 600, second: 400, third: 200 },
    event_requirement: "Participants must bring their own music tracks.",
    event_guidlines: ["No vulgar content", "Performance limited to 5 minutes"],
  },
  {
    event_category: "kala-utsav",
    event_name: "sculpture-contest",
    event_date: "2025-04-05",
    event_time: "3:00PM",
    event_organizer: "Sculptors Club",
    event_location: "Workshop Room",
    event_description: "Create a sculpture within the given theme.",
    event_image: "sculpture_event_poster",
    event_link: "registration_link",
    entry_fees: 90,
    prize_money: { first: 500, second: 300, third: 200 },
    event_requirement: "Basic tools will be provided.",
    event_guidlines: ["Must use provided materials", "Time limit: 2 hours"],
  },
  {
    event_category: "kala-utsav",
    event_name: "origami-challenge",
    event_date: "2025-04-06",
    event_time: "4:00PM",
    event_organizer: "Paper Art Club",
    event_location: "Art Hall",
    event_description: "Show your skills in paper folding techniques.",
    event_image: "origami_event_poster",
    event_link: "registration_link",
    entry_fees: 60,
    prize_money: { first: 300, second: 200, third: 100 },
    event_requirement: "Participants must bring their own paper sheets.",
    event_guidlines: ["No pre-made folds", "Time limit: 45 minutes"],
  },

  {
    event_category: "rang-utsav",
    event_name: "color-fest",
    event_date: "2025-04-07",
    event_time: "2:00PM",
    event_organizer: "Cultural Committee",
    event_location: "Open Grounds",
    event_description:
      "Celebrate colors with traditional performances and fun games.",
    event_image: "color_fest_poster",
    event_link: "registration_link",
    entry_fees: 100,
    prize_money: { first: 500, second: 300, third: 200 },
    event_requirement: "Wear white clothes for the best experience.",
    event_guidlines: ["No harmful colors", "Respect personal space"],
  },
  {
    event_category: "rang-utsav",
    event_name: "holi-beats",
    event_date: "2025-04-06",
    event_time: "5:00PM",
    event_organizer: "Music Club",
    event_location: "Main Stage",
    event_description:
      "Groove to the beats of live DJs and dhol performances with a splash of colors.",
    event_image: "holi_beats_poster",
    event_link: "registration_link",
    entry_fees: 150,
    prize_money: { first: 700, second: 400, third: 250 },
    event_requirement: "Bring a water gun and wear white clothes.",
    event_guidlines: ["No water wastage", "Use only organic colors"],
  },
  {
    event_category: "rang-utsav",
    event_name: "splash-mania",
    event_date: "2025-04-07",
    event_time: "11:00AM",
    event_organizer: "Sports Committee",
    event_location: "Central Lawn",
    event_description:
      "Join the ultimate water and color fight with exciting relay games.",
    event_image: "splash_mania_poster",
    event_link: "registration_link",
    entry_fees: 120,
    prize_money: { first: 600, second: 350, third: 200 },
    event_requirement: "Carry a towel and extra clothes.",
    event_guidlines: ["No pushing or rough play", "Use water responsibly"],
  },
  {
    event_category: "rang-utsav",
    event_name: "rangoli-battle",
    event_date: "2025-04-06",
    event_time: "3:00PM",
    event_organizer: "Arts Club",
    event_location: "Auditorium Foyer",
    event_description:
      "Compete in a vibrant Rangoli-making competition and showcase your creativity.",
    event_image: "rangoli_battle_poster",
    event_link: "registration_link",
    entry_fees: 80,
    prize_money: { first: 500, second: 300, third: 150 },
    event_requirement: "Participants must bring their own Rangoli colors.",
    event_guidlines: [
      "Only organic colors allowed",
      "Work must be completed within the given time",
    ],
  },
  {
    event_category: "rang-utsav",
    event_name: "glow-night",
    event_date: "2025-04-07",
    event_time: "8:00PM",
    event_organizer: "Cultural Committee",
    event_location: "Amphitheater",
    event_description:
      "Experience a neon-themed color party with UV lights and music.",
    event_image: "glow_night_poster",
    event_link: "registration_link",
    entry_fees: 200,
    prize_money: { first: 1000, second: 600, third: 300 },
    event_requirement: "Wear white or neon outfits for the best effect.",
    event_guidlines: ["No outside colors allowed", "Respect personal space"],
  },
  {
    event_category: "thrill-arena",
    event_name: "adventure-rush",
    event_date: "2025-05-10",
    event_time: "10:00AM",
    event_organizer: "Adventure Club",
    event_location: "Outdoor Obstacle Course",
    event_description:
      "Conquer thrilling obstacle courses and push your limits!",
    event_image: "adventure_rush_poster",
    event_link: "registration_link",
    entry_fees: 250,
    prize_money: { first: 1000, second: 600, third: 300 },
    event_requirement: "Wear sports shoes and comfortable clothing.",
    event_guidelines: ["Follow safety instructions", "No shortcuts allowed"],
  },
  {
    event_category: "thrill-arena",
    event_name: "escape-room-challenge",
    event_date: "2025-05-11",
    event_time: "2:00PM",
    event_organizer: "Puzzle Masters",
    event_location: "Mystery Zone",
    event_description:
      "Solve puzzles and riddles to escape before time runs out!",
    event_image: "escape_room_poster",
    event_link: "registration_link",
    entry_fees: 150,
    prize_money: { first: 800, second: 500, third: 250 },
    event_requirement: "Form a team of 3-5 members.",
    event_guidelines: [
      "No external help allowed",
      "Follow room rules strictly",
    ],
  },
  {
    event_category: "thrill-arena",
    event_name: "haunted-house",
    event_date: "2025-05-10",
    event_time: "7:00PM",
    event_organizer: "Horror Club",
    event_location: "Abandoned Mansion",
    event_description:
      "Face your fears in a spine-chilling haunted house experience!",
    event_image: "haunted_house_poster",
    event_link: "registration_link",
    entry_fees: 200,
    prize_money: { first: 700, second: 400, third: 200 },
    event_requirement: "Not for the faint-hearted!",
    event_guidelines: [
      "No touching the actors",
      "Exit anytime if uncomfortable",
    ],
  },
  {
    event_category: "thrill-arena",
    event_name: "paintball-warfare",
    event_date: "2025-05-12",
    event_time: "4:00PM",
    event_organizer: "Battle Zone Club",
    event_location: "Combat Arena",
    event_description:
      "Engage in an intense paintball battle with strategic teamwork!",
    event_image: "paintball_warfare_poster",
    event_link: "registration_link",
    entry_fees: 300,
    prize_money: { first: 1200, second: 800, third: 500 },
    event_requirement: "Wear protective gear provided at the venue.",
    event_guidelines: [
      "No removing masks during play",
      "Respect fair play rules",
    ],
  },
  {
    event_category: "thrill-arena",
    event_name: "bungee-jump-frenzy",
    event_date: "2025-05-13",
    event_time: "3:00PM",
    event_organizer: "Extreme Sports Committee",
    event_location: "Sky Tower",
    event_description:
      "Experience an adrenaline-pumping bungee jump from 150 feet!",
    event_image: "bungee_jump_poster",
    event_link: "registration_link",
    entry_fees: 500,
    prize_money: { first: 2000, second: 1200, third: 800 },
    event_requirement: "Participants must sign a waiver before the jump.",
    event_guidelines: [
      "Medical clearance required",
      "Follow instructor’s commands strictly",
    ],
  },
  {
    event_category: "fashion-show",
    event_name: "glamour-night",
    event_date: "2025-06-15",
    event_time: "7:00PM",
    event_organizer: "Fashion Club",
    event_location: "Grand Auditorium",
    event_description:
      "Showcase your fashion sense on the grand runway with dazzling lights!",
    event_image: "glamour_night_poster",
    event_link: "registration_link",
    entry_fees: 300,
    prize_money: { first: 1500, second: 1000, third: 500 },
    event_requirement: "Participants must bring their own outfits.",
    event_guidelines: [
      "No offensive attire",
      "Follow time slots for performance",
    ],
  },
  {
    event_category: "fashion-show",
    event_name: "ethnic-elegance",
    event_date: "2025-06-16",
    event_time: "6:00PM",
    event_organizer: "Cultural Committee",
    event_location: "Heritage Hall",
    event_description:
      "A celebration of traditional attires from different cultures!",
    event_image: "ethnic_elegance_poster",
    event_link: "registration_link",
    entry_fees: 250,
    prize_money: { first: 1200, second: 800, third: 400 },
    event_requirement: "Wear ethnic or traditional outfits.",
    event_guidelines: [
      "Respect cultural representation",
      "No last-minute outfit changes",
    ],
  },
  {
    event_category: "fashion-show",
    event_name: "futuristic-fashion",
    event_date: "2025-06-17",
    event_time: "5:00PM",
    event_organizer: "Design & Innovation Club",
    event_location: "Expo Center",
    event_description:
      "Step into the future with bold, high-tech fashion styles.",
    event_image: "futuristic_fashion_poster",
    event_link: "registration_link",
    entry_fees: 350,
    prize_money: { first: 1800, second: 1200, third: 600 },
    event_requirement: "Wear futuristic-themed outfits.",
    event_guidelines: ["Use innovative designs", "Props should be lightweight"],
  },
  {
    event_category: "fashion-show",
    event_name: "retro-revival",
    event_date: "2025-06-18",
    event_time: "4:00PM",
    event_organizer: "Vintage Club",
    event_location: "Classic Theater",
    event_description:
      "Rewind time and showcase retro fashion from the past decades!",
    event_image: "retro_revival_poster",
    event_link: "registration_link",
    entry_fees: 200,
    prize_money: { first: 1000, second: 700, third: 300 },
    event_requirement: "Dress in a retro style from the 70s, 80s, or 90s.",
    event_guidelines: ["No modern accessories", "Follow retro theme strictly"],
  },
  {
    event_category: "fashion-show",
    event_name: "runway-royalty",
    event_date: "2025-06-19",
    event_time: "8:00PM",
    event_organizer: "Luxury Fashion Association",
    event_location: "VIP Lounge",
    event_description:
      "A high-end fashion show featuring elegant and luxury designer outfits.",
    event_image: "runway_royalty_poster",
    event_link: "registration_link",
    entry_fees: 500,
    prize_money: { first: 2500, second: 1500, third: 800 },
    event_requirement: "Wear premium or designer outfits.",
    event_guidelines: ["No casual wear", "Maintain poise and professionalism"],
  },

  {
    event_category: "rang-riwaaz",
    event_name: "folk-dance-festival",
    event_date: "2025-07-10",
    event_time: "6:00PM",
    event_organizer: "Cultural Committee",
    event_location: "Heritage Stage",
    event_description:
      "Experience the beauty of traditional folk dances from different regions!",
    event_image: "folk_dance_festival_poster",
    event_link: "registration_link",
    entry_fees: 150,
    prize_money: { first: 1000, second: 700, third: 400 },
    event_requirement: "Participants must wear traditional dance attire.",
    event_guidelines: [
      "No modern dance styles",
      "Respect cultural authenticity",
    ],
  },
  {
    event_category: "rang-riwaaz",
    event_name: "handicraft-exhibition",
    event_date: "2025-07-11",
    event_time: "11:00AM",
    event_organizer: "Art & Crafts Society",
    event_location: "Exhibition Hall",
    event_description:
      "Showcase and appreciate exquisite handmade crafts and artwork.",
    event_image: "handicraft_exhibition_poster",
    event_link: "registration_link",
    entry_fees: 100,
    prize_money: { first: 800, second: 500, third: 300 },
    event_requirement: "Participants must submit their crafts in advance.",
    event_guidelines: ["Only handmade items allowed", "No plagiarism"],
  },
  {
    event_category: "rang-riwaaz",
    event_name: "traditional-music-concert",
    event_date: "2025-07-12",
    event_time: "7:30PM",
    event_organizer: "Music Club",
    event_location: "Open Grounds",
    event_description:
      "Enjoy a mesmerizing evening of classical and folk music performances.",
    event_image: "traditional_music_concert_poster",
    event_link: "registration_link",
    entry_fees: 200,
    prize_money: { first: 1200, second: 800, third: 500 },
    event_requirement: "Musicians must bring their own instruments.",
    event_guidelines: [
      "Only traditional music allowed",
      "Respect other performers",
    ],
  },
  {
    event_category: "rang-riwaaz",
    event_name: "heritage-fashion-show",
    event_date: "2025-07-13",
    event_time: "5:00PM",
    event_organizer: "Fashion & Culture Club",
    event_location: "Grand Auditorium",
    event_description:
      "Walk the runway in stunning traditional outfits from diverse cultures.",
    event_image: "heritage_fashion_show_poster",
    event_link: "registration_link",
    entry_fees: 250,
    prize_money: { first: 1500, second: 1000, third: 600 },
    event_requirement:
      "Outfits must be culturally appropriate and traditional.",
    event_guidelines: ["No fusion outfits", "Respect cultural significance"],
  },
  {
    event_category: "rang-riwaaz",
    event_name: "cuisine-festival",
    event_date: "2025-07-14",
    event_time: "1:00PM",
    event_organizer: "Food Lovers Club",
    event_location: "Food Court",
    event_description:
      "Taste and explore authentic traditional dishes from different regions.",
    event_image: "cuisine_festival_poster",
    event_link: "registration_link",
    entry_fees: 200,
    prize_money: { first: 1300, second: 900, third: 500 },
    event_requirement:
      "Dishes must be freshly prepared and represent a cultural heritage.",
    event_guidelines: [
      "No artificial flavors",
      "Food hygiene must be maintained",
    ],
  },
];

export interface EventDataInterface {
  event_category: string;
  event_name: string;
  event_date: string;
  event_time: string;
  event_organizer: string;
  event_location: string;
  event_description: string;
  event_image: string;
  event_link: string;
  entry_fees: number;
  prize_money: {
    first: number;
    second: number;
    third: number;
  };
  event_requirement: string;
  event_guidelines?: string[];
}
