export const EVENT_DETAILS = [
  //   KALAA UTSAV
  {
    event: "dance-competition",
    eventName: "Dance Competition",
    category: "kalaa-utsav",
    description: "Showcase your talent in an energetic and expressive dance competition.",
    eligibility: [
      "Open to all currently enrolled college students.",
      "Teams must consist of 3–10 members. Solo and duo performances are allowed.",
    ],
    categories: [
      "Classical",
      "Hip-Hop",
      "Contemporary",
      "Freestyle",
      "Bollywood",
    ],
    registration: [
      "Participants must register before the deadline. Late entries will not be accepted.",
      "Music must be submitted in MP3 format before the event.",
    ],
    performance_Rules: [
      "Time Limit: 3 to 5 minutes.",
      "Props must be provided by participants.",
      "Costumes should be appropriate and respectful.",
      "Music must be submitted in advance.",
      "Any dance style is allowed unless restricted.",
    ],
    judging_Criteria: {
      choreography: "Creativity, originality, and execution (20%)",
      technique: "Precision, control, and difficulty level (20%)",
      synchronization:
        "Coordination among team members (for group performances) (20%)",
      performance_Quality: "Expression, stage presence, and confidence (20%)",
      audience_Engagement:
        "Connection with the audience, energy, and impact (20%)",
    },
    disqualification: [
      "Exceeding the time limit.",
      "Use of inappropriate content, misconduct, or any disrespectful behavior.",
      "Plagiarism or copying an existing routine.",
    ],
    technical_Requirements: [
      "Participants should bring their music on a USB or device.",
      "Event organizers will provide basic sound and lighting.",
    ],
    code_Of_Conduct: [
      "Participants must arrive at least 1 hour before the event.",
      "All decisions made by the judges will be final and binding.",
    ],
    venue: "LNCT Indore",
    entry_Fee: "50",
    date: "08/04/2025",
    time: "11:30 AM",
    faculty_Coordinator: {
      name: "Shree Sudha Maam",
      contact: "7067884437",
      email: null,
    },
    student_Coordinator: {
      name: "Monalika Khanna",
      contact: "7805060610",
      email: null,
    },
  },

  {
    event: "poetry-slam",
    eventName: "Poetry Slam",
    category: "kalaa-utsav",
    description: "Express emotions, thoughts, and creativity through the art of spoken poetry.",
    eligibility: [
      "Open to all students of every college.",
      "Participants must have valid student ID cards.",
    ],
    categories: ["Hindi Poetry"],
    registration: [
      "Registration is mandatory to participate in the contest.",
      "Last date for registration: will be notified.",
      "Spot registration will NOT be allowed.",
    ],
    performance_Rules: [
      "Time limit for presentation: 3 to 5 minutes.",
      "Use of background music or props is NOT allowed.",
      "Participants must present their poem in person.",
    ],
    judging_Criteria: {
      creativity: "Creativity and originality (33%)",
      language_Expression: "Language and expression (33%)",
      presentation_Impact: "Presentation and impact (34%)",
    },
    disqualification: [
      "Any form of obscenity, offensive language, or disrespectful content will lead to immediate disqualification.",
      "Violation of time limit or submission rules will result in penalty or disqualification.",
    ],
    technical_Requirements: [
      "Participants must submit a typed copy of their poem during registration or on the event day.",
      "The poem must be original. Plagiarism will lead to disqualification.",
      "Word limit: Maximum 40 lines.",
    ],
    code_Of_Conduct: [
      "All decisions made by the judges will be final and binding.",
    ],
    venue: "LNCT Indore",
    entry_Fee: "50",
    date: "08/04/2025",
    time: "11:30 AM",
    faculty_Coordinator: {
      name: "Shree Sudha Maam",
      contact: "7067884437",
      email: null,
    },
    student_Coordinator: {
      name: "Nitin Patel",
      contact: "7441162752",
      email: "rujhanbajpai@gmail.com",
    },
  },
  {
    event: "drama-performance",
    eventName: "Drama Performance",
    category: "kalaa-utsav",
    description: "Experience the magic of theatre and bring characters to life on stage.",
    eligibility: [
      "Open to all currently enrolled college students.",
      "Teams must consist of 5–10 members.",
    ],
    categories: ["Stage Play", "Street Play", "Mime", "Skit"],
    registration: [
      "All participants must register and submit their scripts or outlines by the given deadline.",
      "Late entries will not be accepted.",
    ],
    performance_Rules: [
      "Maximum performance time: 6 minutes (including set changes).",
      "Teams must handle their own props and costumes. The organizers are not responsible for lost items.",
      "No damage to stage property or venue will be tolerated.",
      "Use of fire, hazardous materials, or sharp objects is prohibited.",
    ],
    judging_Criteria: {
      script_Quality: "Originality, depth, and engagement of script (25%)",
      acting_Skills: "Expressions, dialogue delivery, and stage presence (25%)",
      coordination: "Synchronization and teamwork (20%)",
      impact: "Emotional and entertainment value (20%)",
      audience_Engagement: "Connection with the audience (10%)",
    },
    disqualification: [
      "Use of vulgar language, hate speech, or inappropriate content.",
      "Disrespectful handling of sensitive topics (religion, politics, etc.).",
      "Exceeding the time limit.",
      "Any act causing damage to stage property or venue.",
    ],
    technical_Requirements: [
      "Basic sound and lighting will be provided by the organizers.",
      "Teams must inform organizers in advance about any special requirements.",
    ],
    code_Of_Conduct: [
      "The organizers are not liable for injuries during the event.",
      "All decisions made by the judges will be final and binding.",
    ],
    venue: "LNCT Indore",
    entry_Fee: "50",
    date: "08/04/2025",
    time: "11:30 AM",
    faculty_Coordinator: {
      name: "Shree Sudha Maam",
      contact: "7067884437",
      email: null,
    },
    student_Coordinator: {
      name: "Mehak Vijaywargiya",
      contact: "9516844542",
      email: null,
    },
  },

  {
    event: "music-and-performing-arts",
    eventName: "Music & Performing Arts",
    category: "kalaa-utsav",
    description: "Display your musical prowess and performing arts skills on stage.",
    eligibility: [
      "Open to all registered college students across Indore, irrespective of branch, course, or year.",
      "Participants must present their college ID cards for verification.",
    ],
    performance_Time: {
      duration: "3-5 minutes",
      penalty: "Exceeding the time limit will lead to point deduction.",
    },
    language_And_Song_Selection: [
      "Songs can be in Hindi, English, or any Indian regional language.",
      "Lyrics must be appropriate and respectful.",
      "Obscene, offensive, or inappropriate lyrics are strictly prohibited.",
    ],
    music_And_Accompaniment: [
      "Participants may sing a cappella, with backing tracks, or with live instruments.",
      "If using a backing track, it must be provided in MP3 format at the time of registration.",
      "If playing an instrument, participants must bring their own instruments.",
    ],
    content_Guidelines: {
      cultural_Respect: [
        "Songs can be of any genre but should not hurt religious sentiments or national pride.",
      ],
      audience_Sensitivity: [
        "Songs should be engaging and enjoyable while maintaining a respectful tone.",
        "Avoid songs with references to sensitive issues such as caste, religion, gender discrimination, or socio-political controversies.",
      ],
      participant_Respect: [
        "Maintain a positive and encouraging attitude toward fellow participants.",
        "Any attempt to demean or insult others through lyrics or performance style will result in disqualification.",
      ],
    },
    code_Of_Conduct: [
      "Maintain discipline and decorum both on and off stage.",
      "Any misbehavior or disruptive conduct will not be tolerated and may lead to disqualification.",
      "Participants must perform in their own voice. Lip-syncing or mimicking is not allowed.",
      "Plagiarism or copying another singer’s style without originality may result in point deductions.",
    ],
    judging_Criteria: {
      vocal_Quality: "Pitch, tone, breath control, and clarity (20%)",
      expression_And_Stage_Presence:
        "Confidence, emotive expression, audience connection (20%)",
      rhythm_And_Timing: "Synchronization with music, tempo maintenance (20%)",
      song_Selection_And_Impact:
        "Appropriateness, song difficulty, overall impression (20%)",
      adherence_To_Rules: "Following all content and conduct guidelines (20%)",
    },
    decision_And_Disqualification: [
      "The judges' decision will be final and binding.",
      "Any violation of rules will result in immediate disqualification without further discussion.",
    ],
    awards_And_Certificates: [
      "Attractive prizes will be awarded to the top 2 performers.",
      "All participants will receive certificates.",
    ],
    venue: "LNCT Indore",
    entry_Fee: "50",
    date: "08/04/2025",
    time: "11:30 AM",
    faculty_Coordinator: {
      name: "Shree Sudha Maam",
      contact: "7067884437",
      email: null,
    },
    student_Coordinator: {
      name: "Rajveer Goud",
      contact: "9926510065",
      email: null,
    },
  },
  {
    event: "stand-up-comedy-competition",
    eventName: "Stand-Up Comedy Competition",
    category: "kalaa-utsav",
    description: "Make the audience laugh with your wit and humor in this comedy battle.",
    eligibility: [
      "Open to all registered students of SKC LNCT Group of Colleges.",
      "Participants must present their college ID cards for verification.",
    ],
    performance_Time: {
      duration: "5-7 minutes",
      penalty: "Exceeding the time limit will lead to point deduction.",
    },
    language: [
      "Use of slang or regional dialects should be tasteful and respectful.",
      "Profanity, vulgar, or abusive language is strictly prohibited.",
    ],
    content_Guidelines: {
      cultural_Respect: [
        "Content should align with Indian moral values and should not hurt religious sentiments, or mock national symbols, traditions, or dignitaries.",
      ],
      sensitivity_To_Current_Issues: [
        "Participants must avoid references to sensitive topics such as caste, religion, gender identity, or socio-political controversies which could incite unrest or offend any section of society.",
        "Satire is encouraged but must be balanced, respectful, and non-inflammatory.",
      ],
      respect_For_Individuals_And_Groups: [
        "No personal attacks on fellow students, faculty, staff, celebrities, or public figures.",
        "Derogatory remarks against any community, gender, or region will lead to immediate disqualification.",
      ],
    },
    code_Of_Conduct: [
      "Participants must adhere to a decent and modest dress code, reflecting the values of the institution.",
      "Maintain discipline and decorum both on and off stage.",
      "Any misbehavior or disruptive conduct will not be tolerated and may lead to disqualification.",
      "Content must be original. Plagiarism or copying other comedians’ material is strictly prohibited.",
    ],
    judging_Criteria: {
      content_Quality: "Originality, creativity, and relevance (20%)",
      delivery_And_StagePresence:
        "Confidence, voice modulation, audience engagement (20%)",
      timing_And_Flow: "Pacing and transitions (20%)",
      humor_Quotient: "Wit, relatability, and audience reaction (20%)",
      adherence_To_Rules: "Following all content and conduct guidelines (20%)",
    },
    decision_And_Disqualification: [
      "The judges' decision will be final and binding.",
      "Any violation of rules will result in immediate disqualification without further discussion.",
    ],
    awards_And_Certificates: [
      "Attractive prizes will be awarded to the top performers.",
      "All participants will receive certificates.",
    ],
    venue: "LNCT Indore",
    entry_Fee: "50",
    date: "08/04/2025",
    time: "11:30 AM",
    faculty_Coordinator: {
      name: "Shree Sudha Maam",
      contact: "7067884437",
      email: null,
    },
    student_Coordinator: {
      name: "Kuldeep mudgal",
      contact: "7581008074",
      email: null,
    },
  },

  //  RANG RIWAAZ
  {
    event: "poster-making",
    eventName: "Poster Making",
    category: "rang-riwaaz",
    description: "Unleash your creativity and design stunning posters on cultural themes!",
    eligibility: [
      "Open to all registered students of SKC LNCT Group of Colleges.",
      "Participants must present their college ID cards for verification.",
    ],
    rules: [
      "Themes: AI, Spring Season, Mental Health Awareness, Anti-Bullying.",
      "The poster should convey a moral or message.",
      "Sheets will be provided, but participants must bring their own stationery.",
      "Phones are not allowed.",
    ],
    venue: "LNCT Physics Lab",
    entry_Fee: "50",
    date: "08/04/2025",
    time: "10:00am – 12:00pm",
    faculty_Coordinator: {
      name: "Ms. Sayali Kulkarni",
      contact: null,
      email: null,
    },
    student_Coordinator: {
      name: "Deepti Mahisare",
      contact: null,
      email: null,
    },
  },
  {
    event: "rangoli",
    eventName: "Rangoli",
    category: "rang-riwaaz",
    description: "Create vibrant and intricate rangoli designs that showcase your artistic skills.",
    eligibility: [
      "Open to all registered students of SKC LNCT Group of Colleges.",
      "Participants must present their college ID cards for verification.",
    ],
    rules: [
      "Maximum 2 people per group.",
      "Theme: Innovation & Colorful.",
      "1 sq. foot area allotted per Rangoli.",
      "Participants must bring their own rangoli colors.",
      "Phones are not allowed.",
    ],
    venue: "LNCT Lobby",
    entry_Fee: "50",
    date: "08/04/2025",
    time: "12:00pm – 2:00pm",
    faculty_Coordinator: {
      name: "Ms. Rajashree Sahu",
      contact: "7008439345",
      email: null,
    },
    student_Coordinator: {
      name: "Nayanshree Soni",
      contact: null,
      email: null,
    },
  },
  {
    event: "tattoo-making",
    eventName: "Tattoo Making",
    category: "rang-riwaaz",
    description: "Showcase your talent in temporary tattoo artistry with unique and intricate designs.",
    eligibility: [
      "Open to all registered students of SKC LNCT Group of Colleges.",
      "Participants must present their college ID cards for verification.",
    ],
    rules: [
      "Theme: Innovation.",
      "Only hands and neck are allowed for tattoos.",
      "Participants must bring their own colors like sketch pens or colorful pens.",
      "Pre-select the person they want to tattoo.",
      "No phones, no outside help allowed.",
    ],
    venue: "LNCT Physics Lab",
    entry_Fee: "50",
    date: "08/04/2025",
    time: "2:00pm – 3:00pm",
    faculty_Coordinator: {
      name: "Ms. Nikita Yadav",
      contact: "9171125237",
      email: null,
    },
    student_Coordinator: {
      name: "Poonam Sahu",
      contact: null,
      email: null,
    },
  },
  {
    event: "face-painting",
    eventName: "Face Painting",
    category: "rang-riwaaz",
    description: "Transform faces into artistic masterpieces with creative and colorful face painting.",
    eligibility: [
      "Open to all registered students of SKC LNCT Group of Colleges.",
      "Participants must present their college ID cards for verification.",
    ],
    rules: [
      "Theme: Innovation & Colorful.",
      "Only face painting is allowed.",
      "Participants must bring their own colors.",
      "Pre-select the person they want to paint.",
      "No phones, no outside help allowed.",
    ],
    venue: "LNCT Physics Lab",
    entry_Fee: "50",
    date: "08/04/2025",
    time: "2:30pm – 3:30pm",
    faculty_Coordinator: {
      name: "Ms. Nikita Yadav",
      contact: "9171125237",
      email: null,
    },
    student_Coordinator: {
      name: "Vaishali Sahu",
      contact: null,
      email: null,
    },
  },

  //   TECH SPARDHA
  {
    event: "code-clash",
    eventName: "Code Clash",
    category: "tech-spardha",
    description : "A fast-paced coding quiz testing your knowledge of programming, algorithms, and logic.",
    date: "07/04/2025",
    time: "12:50pm - 1:40pm",
    venue: "LNCT Server Room",
    entry_Fee: "75",
    prize_Money: {
        first: "500",
        second: "300",
        third: "200",
    },
    student_Coordinator: {
      name: "Utsav Jaiswal",
      email: "masterutsav.in@gmail.com",
      contact: null,
    },
    faculty_Coordinator: {
      name: "Mrs. Shrashti Thakur",
      contact: "9691185077",
      email: null,
    },
    eligibility: ["Student must have to reach 10 minutes before the start time of quiz." , "Student must have to show the email where they get token for that quiz."],
    rules: [
      "You must complete all 20 questions within the allocated time (40 minutes).",
      "Token is valid only for 1 attempt.",
      "+2 for each correct answer, -0.5 for each incorrect answer.",
      "Switching tabs, exiting fullscreen mode, refreshing the page, or hiding the tab for more than 30s will result in auto-submission.",
      "External resources, libraries, or AI tools are not allowed during the competition.",
      "Taking snapshots/screenshots is not allowed. Mobile phones are not allowed.",
      "If scores clash, quiz submission time will be considered.",
      "In case of technical issues, contact the support team immediately.",
    ],
  },
  {
    event: "bug-bash",
    eventName: "Bug Bash",
    category: "tech-spardha",
    description: "Find and fix hidden bugs in given programs within a limited time.",
    date: "07/04/2025",
    time: "1:40pm - 2:30pm",
    venue: "LNCT Server Room",
    entry_Fee: "75",
    prize_Money: {
        first: "500",
        second: "300",
        third: "200",
    },
    student_Coordinator: {
      name: "Utsav Jaiswal",
      email: "masterutsav.in@gmail.com",
      contact: null,
    },
    faculty_Coordinator: {
      name: "Mrs. Shrashti Thakur",
      contact: "9691185077",
      email: null,
    },
    eligibility: ["Student must have to reach 10 minutes before the start time of quiz." , "Student must have to show the email where they get token for that quiz."],
    rules: [
      "You will be given faulty code that you must fix.",
      "Plagiarism will result in immediate disqualification.",
      "No intellisence is given in the code editor.",
      "Token is valid only for the first attempt.",
      "You must complete the competition within the allocated time (40 minutes).",
      "+4 for each correct answer, -1 for each incorrect answer.",
      "You may use any programming language supported by the platform.",
      "External resources, libraries, or AI tools are not allowed during the competition.",
      "Do not refresh the tab or exit fullscreen mode after the quiz starts.",
      "Do not switch tabs or stay away for more than 30 seconds, otherwise, the test will auto-submit.",
      "You can submit your solution multiple times, but only your first submission will be considered.",
      "If scores clash, quiz submission time will be considered.",
      "In case of technical issues, contact the support team immediately.",
    ],
  },
  {
    event: "code-mirage",
    eventName: "Code Mirage",
    category: "tech-spardha",
    description: "Recreate the exact code structure based on given outputs, testing logical deduction.",
    date: "07/04/2025",
    time: "2:30pm - 3:20pm",
    venue: "LNCT Server Room",
    entry_Fee: "75",
    prize_Money: {
        first: "500",
        second: "300",
        third: "200",
    },
    student_Coordinator: {
      name: "Utsav Jaiswal",
      email: "masterutsav.in@gmail.com",
      contact: null,
    },
    faculty_Coordinator: {
      name: "Mrs. Shrashti Thakur",
      contact: "9691185077",
      email: null,
    },
    eligibility: ["Student must have to reach 10 minutes before the start time of quiz." , "Student must have to show the email where they get token for that quiz."],
    rules: [
      "You must finish your project within the time limit of 40 minutes.",
      "No intellisence is given in the code editor.",
      "Good command on html and css are enough to participate in this mirage.",
      "Switching tabs, taking snapshots, exiting fullscreen mode, or being away for more than 30 seconds will result in auto-submission.",
      "Your code will be reviewed by the event organizer.",
    ],
  },
  {
    event: "illustratex",
    eventName: "IllustrateX (Vector Art Designing)",
    category: "tech-spardha",
    description : "A fast-paced coding quiz testing your knowledge of programming, algorithms, and logic.",
    date: "07/04/2025",
    time: "2:30pm - 3:30pm",
    venue: "LNCT Boss Lab",
    entry_Fee: "75",
    prize_Money: {
        first: "500",
        second: "300",
        third: "200",
    },
    eligibility: [
      "Open to all students of every college.",
      "Participants must have valid student ID cards.",
    ],
    registration: [
      "Registration is mandatory to participate in the contest.",
      "Last date for registration: will be notified.",
      "Spot registration will NOT be allowed.",
    ],
    theme: "Theme will be given randomly during the event.",
    submission_Guidelines: ["Size: A3/A2", "Format: JPEG/PNG/PDF (300 DPI)"],
    judging_Criteria: [
      "Creativity",
      "Relevance",
      "Aesthetics",
      "Message Clarity",
      "Neatness",
    ],
    disqualification: ["No AI-Generated Posters"],
    decision: "Judges' decision is final.",
    requirements: [
      "Bring your own laptop.",
      "Any favorable software like Canva, Adobe, etc.",
    ],
    faculty_Coordinator: {
      name: "Mrs. Shrashti Thakur",
      contact: "9691185077",
      email: null,
    },
    student_Coordinator: {
      name: "Pankaj Vairagi",
      contact: "6261029938",
      email: null,
    },
  },
];
